sudo: false
env: RELEASE_TESTING=1
language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
install:
  - cpanm --quite --notest Dancer::Session::Cookie Dancer::Plugin::DBIC Dancer::Session::DBIC DBD::SQLite Dancer::Session::JSON Dancer::Session::Storable
  - cpanm --quiet --installdeps --notest .
